const LOGIN_FAILED = 'LOGIN_FAILED'
const LOGIN_STARTED = 'LOGIN_STARTED'
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGOUT = 'LOGOUT'

export default {
    LOGIN_FAILED,
    LOGIN_STARTED,
    LOGIN_SUCCESS,
    LOGOUT
}
